# This is our DEVELOPMENT dockerfile.
FROM ruby:2.6.2-stretch

RUN apt-get update \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get install -y libqtwebkit4 libqt4-dev xvfb \
    && rm -rf /var/lib/apt/lists/*

RUN gem install bundler

EXPOSE 3000

WORKDIR /share
ADD Gemfile /share/Gemfile
ADD Gemfile.lock /share/Gemfile.lock
RUN bundle install --with development

ADD ./ /share
